### ISSUE TITLE
"CompileError - undefined function browser/2" when adding content plug to router.ex

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/content#15]
Following the instructions in the readme file, I was faced with this error `(CompileError) undefined function browser/2 (expected HitsWeb.Router to define such a function or for it to be imported, but none are available)` when adding the content plug to the router pipeline.

The error could be obvious to some but as someone who is starting out, it's not clear in the README that one has to also change the `pipe_through` to `pipe_through(:any)` in the `scope` method inside the`router.ex` file as well.

I can create a PR with this small change to be more clear to a newbie audience 😄 .

**Comment by nelsonic** [comment]
@LuchoTurtle Thank you for opening this issue. 👍  Clearly something isn't right. 😕 
From the error, you appear to be trying to run `content` in the `Hits` project. 
Most likely part of https://github.com/dwyl/hits/issues/168 💭 

Is that correct? 👍
