### ISSUE TITLE
Any URL should return JSON when ".json" is appended

### ISSUE THREAD

**Issue by nelsonic** [dwyl/content#3]
As a person using the @dwyl App who also wants to build my own custom interface,
I want to be able to append `.json` to any URL in the App 
and see a `JSON` representation of the content (data)
without having to manually construct an API request.
i.e. use the existing session/JWT and return the data for the given (logged in) person.

Reddit does this for most of their URLs. e.g: [reddit.com/r/politics/comments/gpuwml/trump_rips_columbia_as_disgraceful_institution
](https://www.reddit.com/r/politics/comments/gpuwml/trump_rips_columbia_as_disgraceful_institution/)

![image](https://user-images.githubusercontent.com/194400/82817216-7eec8680-9e94-11ea-8475-6d6c2f022a72.png)

But appending the `.json` to the end of the URL:
[reddit.com/r/politics/comments/gpuwml/trump_rips_columbia_as_disgraceful_institution/.json
](https://www.reddit.com/r/politics/comments/gpuwml/trump_rips_columbia_as_disgraceful_institution/.json)
![image](https://user-images.githubusercontent.com/194400/82817288-a3e0f980-9e94-11ea-98e3-5d3ecd97bf78.png)

# Todo

+ [x] add `accept=json` Header if the url contains `".json"`
+ [x] Demo it in the tutorial: https://github.com/dwyl/phoenix-content-negotiation-tutorial#part-2

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/content/1.1.0 contains @SimonLab's PR #4 📦 :shipit:

**Comment by nelsonic** [comment]
After reading https://github.com/dwyl/phoenix-content-negotiation-tutorial/pull/4#discussion_r430524222 I realise that I haven't fully _explained_ how this should work.
Instead of having a separate route to match the `get /.json`, the `.json` should be stripped from the URL and the `get /` should match it but with the `accept` header updated to `application/json` so the controller knows what type of content to return. 💭

**Comment by SimonLab** [comment]
Not that a pipe is called after matching a url:
https://hexdocs.pm/phoenix/Phoenix.Router.html#module-pipelines-and-plugs
![image](https://user-images.githubusercontent.com/6057298/82927838-35c23280-9f79-11ea-8a60-109f7e9c6d95.png)

**Comment by nelsonic** [comment]
Sounds like we will need to have a Pokemon route 
https://stackoverflow.com/questions/32189311/catch-all-wildcard-route-in-elixirs-phoenix
and then Redirect back to the router with the `.json` stripped. 💭

**Comment by nelsonic** [comment]
Attempting to redirect in the `Content.call/2` but,
Seeing:
```
 ** (RuntimeError) expected connection to have a response but no response was set/sent.
     Please verify that you assign to "conn" after a request
```
Looks like we need to do the redirecting inside a handler in the consumer app. 💭

**Comment by nelsonic** [comment]
Investigating the possibility of using a `forward` in `router.ex` to 
`forward "*.json", ???, path: "*"
https://hexdocs.pm/phoenix/routing.html#forward

But it appears that wildcards are not allowed in `forward/4` ... 🤦

**Comment by nelsonic** [comment]
```elixir
iex(4)> AppWeb.Router.__routes__()
[
  %Phoenix.Router.Route{
    assigns: %{},
    helper: "quotes",
    host: nil,
    kind: :match,
    line: 20,
    metadata: %{log: :debug},
    path: "/",
    pipe_through: [:any],
    plug: AppWeb.QuotesController,
    plug_opts: :index,
    private: %{},
    trailing_slash?: false,
    verb: :get
  }
]
```

**Comment by nelsonic** [comment]
My plan is to use the [`apply/3`](https://hexdocs.pm/elixir/Kernel.html#apply/3) to invoke the correct controller based on `conn.request_path`.

**Comment by nelsonic** [comment]
This is working:

```elixir
# AppWeb.Router
get "/*pokemon", QuotesController, :redirect_json
```

```elixir
  # AppWeb.QuotesController
  def redirect_json(conn, params) do
    route = Enum.filter(AppWeb.Router.__routes__(), fn x -> 
      x.path == conn.request_path
    end) |> List.first
    apply(route.plug, route.plug_opts, [conn, params])
  end
```

I'm working on putting this into `Content` 🧑‍💻

**Comment by nelsonic** [comment]
The hardest part about this is writing the tests ... 💭

**Comment by nelsonic** [comment]
Got the tests working for the "Happy Path" 🙌 

But when the underlying route does not exist e.g: http://localhost:4000/invalid.json then it fails _ugly_!
![image](https://user-images.githubusercontent.com/194400/83024404-3e247700-a026-11ea-936c-ef41de9ac63e.png)

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/content/1.2.5

**Comment by nelsonic** [comment]
A marginally more friendly error message displayed:
![image](https://user-images.githubusercontent.com/194400/83032923-5d270700-a02e-11ea-8c6c-2b1b5a39b58a.png)
With advice for

**Comment by nelsonic** [comment]
`JSON` in Firefox web browser:
![image](https://user-images.githubusercontent.com/194400/83065081-c3c21a00-a05a-11ea-8adb-063606fbf4bb.png)

**Comment by nelsonic** [comment]
PRs for this issue:
+ https://github.com/dwyl/content/pull/6
+ https://github.com/dwyl/phoenix-content-negotiation-tutorial/pull/4

**Comment by nelsonic** [comment]
see: https://phoenix-content-negotiation.herokuapp.com/.json
![wake-sleeping-heroku-app](https://phoenix-content-negotiation.herokuapp.com/ping)
