### ISSUE TITLE
Inês Talk

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/content#4]
Potential speaking slot for Inês?

[#BeBoldForChange - The Women Using Tech to Empower Others](https://www.meetup.com/techforgood/events/237579805/)

Tech For Good

**Comment by iteles** [comment]
@markwilliamfirth Might be a good place to drop in a link?

**Comment by markwilliamfirth** [comment]
Updated with link! Next step is to contact Ellie to ask (if you're happy to go ahead) - I'm happy to do this, unless you would prefer to?

**Comment by iteles** [comment]
If it's Ellie, we might want to clarify upfront that it'll be about dwyl things and not F&C 👍

**Comment by markwilliamfirth** [comment]
Have contacted Ellie - waiting on response 👍
